version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db

  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
      ME_CONFIG_MONGODB_SERVER: mongo  
      ME_CONFIG_MONGODB_PORT: 27017     
    ports:
      - "8081:8081"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reviewsdb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
